# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dodl < Formula
    desc "A cli tool that automates the creation and organisation of structured documents using custom templates."
    homepage "https://github.com/matthewchivers/dodl"
    version "0.2.2"
    license "MIT"
  
    depends_on "go"
  
    on_macos do
      on_intel do
        url "https://github.com/matthewchivers/dodl/releases/download/v0.2.2/dodl_Darwin_x86_64.tar.gz"
        sha256 "1b9a0b025a96c81ab5f99a209e69e89a3855f8dbf967c2ae1bc9197e2d8bc5a4"
  
        def install
          bin.install "dodl"
        end
      end
      on_arm do
        url "https://github.com/matthewchivers/dodl/releases/download/v0.2.2/dodl_Darwin_arm64.tar.gz"
        sha256 "569d338a08e35692a3af7cc77b6721522d2020e235f43a3df1c96bfd948b236d"
  
        def install
          bin.install "dodl"
        end
      end
    end
  
    on_linux do
      on_intel do
        if Hardware::CPU.is_64_bit?
          url "https://github.com/matthewchivers/dodl/releases/download/v0.2.2/dodl_Linux_x86_64.tar.gz"
          sha256 "7953cce65d0170c7cfe1b39fd946e1dad1276d29217e2cfe9cda3c1e634aa582"
  
          def install
            bin.install "dodl"
          end
        end
      end
      on_arm do
        if Hardware::CPU.is_64_bit?
          url "https://github.com/matthewchivers/dodl/releases/download/v0.2.2/dodl_Linux_arm64.tar.gz"
          sha256 "e899d60c209db1999e2cf64b077dc057ccbd5ab7180b2029b00ce3ee93bf2a4d"
  
          def install
            bin.install "dodl"
          end
        end
      end
    end
  
    def caveats
      <<~EOS
        Note: This formula only supports macOS and Linux
      EOS
    end
  
    test do
      system "#{bin}/dodl --version"
    end
  end
  